name: DemonstraÃ§Ã£o de AÃ§Ãµes do GitHub
run-name: ğŸš€ O explorador ${{ github.actor }} estÃ¡ testando as AÃ§Ãµes do GitHub!
on: [push]
jobs:
  Explorando-Acoes-GitHub:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ ParabÃ©ns! O job foi acionado automaticamente pelo evento ${{ github.event_name }}."
      - run: echo "ğŸ§ O job estÃ¡ sendo executado em um servidor ${{ runner.os }} hospedado pelo GitHub!"
      - run: echo "ğŸ” VocÃª estÃ¡ trabalhando na branch ${{ github.ref }} do repositÃ³rio ${{ github.repository }}."
      - name: Preparar cÃ³digo do repositÃ³rio
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ O repositÃ³rio ${{ github.repository }} foi clonado com sucesso para o ambiente do runner."
      - run: echo "ğŸ–¥ï¸ O workflow agora estÃ¡ pronto para executar e testar seu cÃ³digo."
      - name: Listar arquivos do repositÃ³rio
        run: |
          echo "ğŸ—‚ï¸ Listando os arquivos do repositÃ³rio:"
          ls ${{ github.workspace }}
      - run: echo "ğŸ Status final do job: ${{ job.status }}. Excelente trabalho! ğŸš€"
