name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  DB_MONGO_HOST: ${{ vars.DB_MONGO_HOST }}
  DB_MONGO_NAME: ${{ vars.DB_MONGO_NAME }}
  DB_MONGO_USER: ${{ vars.DB_MONGO_USER }}
  DB_MONGO_PASSWORD: ${{ secrets.DB_MONGO_PASSWORD }}
  DOCKER_REGISTRY: "docker.io"
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: "tofood/backend"
  CLUSTER_NAME: "tofood-eks-cluster"
  DEPLOYMENT_NAME: "tofood-deployment"
  NODEGROUP_NAME: "tofood-nodegroup"

jobs:
  # Job de Build do Projeto Node/TypeScript
  build_project:
    name: üõ†Ô∏è Build do Projeto
    runs-on: ubuntu-latest

    steps:
      - name: üé® Checkout do reposit√≥rio
        uses: actions/checkout@v4

      - name: üì¶ Instalar depend√™ncias
        run: npm install

      - name: üõ†Ô∏è Build do projeto
        run: npm run build

  # Job de Teste
  test:
    name: üß™ Testes da Aplica√ß√£o
    runs-on: ubuntu-latest
    needs: build_project

    steps:
      - name: üé® Checkout do reposit√≥rio
        uses: actions/checkout@v4

      - name: üì¶ Instalar depend√™ncias
        run: npm install

      - name: üß™ Executar Testes
        run: npm test

  # Job de Lint
  lint:
    name: üé® Lint - Valida√ß√£o do C√≥digo
    runs-on: ubuntu-latest
    needs: build_project

    steps:
      - name: üé® Checkout do reposit√≥rio
        uses: actions/checkout@v4

      - name: üì¶ Instalar depend√™ncias
        run: npm install

      - name: üîç Rodar Lint
        run: npm run lint

  # Teste de Conex√£o com AWS
  aws_test_connection:
    name: üì¶ Teste de Conex√£o com AWS
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: üé® Fazer checkout do reposit√≥rio
        uses: actions/checkout@v4

      - name: üöÄ Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: üìÉ Instalar depend√™ncias
        run: npm install aws-sdk

      - name: üì¶ Testar conex√£o com a AWS
        run: |
          node -e "
          const AWS = require('aws-sdk');
          AWS.config.update({
            region: process.env.AWS_REGION,
            accessKeyId: process.env.AWS_ACCESS_KEY_ID,
            secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
            sessionToken: process.env.AWS_SESSION_TOKEN
          });
          async function testConnection() {
            try {
              const s3 = new AWS.S3();
              const result = await s3.listBuckets().promise();
              console.log('‚ú® Conex√£o bem-sucedida com a AWS! Buckets:', result.Buckets.map(bucket => bucket.Name).join(', '));
            } catch (error) {
              console.error('‚ùå Falha ao conectar √† AWS:', error.message);
              process.exit(1);
            }
          }
          testConnection();
          "

  # Teste de Conex√£o com MongoDB
  mongodb_test:
    name: üóÑÔ∏è Teste de Conex√£o com MongoDB
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: üé® Fazer checkout do reposit√≥rio
        uses: actions/checkout@v4
      - name: üöÄ Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: üì¶ Instalar depend√™ncias
        run: npm install mongodb
      - name: Testar conex√£o com o MongoDB
        run: |
          node -e "
          const { MongoClient } = require('mongodb');
          const uri = 'mongodb+srv://' + process.env.DB_MONGO_USER + ':' + process.env.DB_MONGO_PASSWORD + '@' + process.env.DB_MONGO_HOST + '/' + process.env.DB_MONGO_NAME + '?retryWrites=true&w=majority';
          console.log('üîç Tentando conex√£o com a URI:', uri.replace(process.env.DB_MONGO_PASSWORD, '****'));
          const client = new MongoClient(uri, { useUnifiedTopology: true });
          async function run() {
            try {
              await client.connect();
              console.log('‚ú® Conex√£o bem-sucedida com o MongoDB!');
            } catch (error) {
              console.error('‚ùå Falha ao conectar ao MongoDB:', error.message);
              process.exit(1);
            } finally {
              await client.close();
            }
          }
          run();
          "

  # Teste de Build da Imagem Docker
  docker_build_test:
    name: üêã Teste de Build da Imagem Docker
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'pull_request'

    steps:
      - name: üé® Fazer checkout do reposit√≥rio
        uses: actions/checkout@v4
      - name: üêã Login no Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin
      - name: üõ†Ô∏è Build da imagem Docker
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:latest .
      - name: üè∑Ô∏è Tag da imagem
        run: |
          docker tag $DOCKER_REGISTRY/$IMAGE_NAME:latest $DOCKER_REGISTRY/$IMAGE_NAME:${{ github.sha }}
      - name: ‚úÖ Logout do Docker
        run: docker logout $DOCKER_REGISTRY

  # Job para mensagem de PR sucesso
  pr_status:
    name: ‚úÖ Tudo certo!
    runs-on: ubuntu-latest
    needs: [mongodb_test, docker_build_test]
    if: github.event_name == 'pull_request'

    steps:
      - name: Aprova√ß√£o do PR
        run: |
          echo "Todos os testes passaram. Pipeline conclu√≠do PR aprovado ‚úÖ."

  # Job de Configura√ß√£o Inicial para Deploy (somente em merges para main)
  setup:
    name: üõú Estabelecendo conex√£o com AWS
    runs-on: ubuntu-latest
    needs: [test, lint, aws_test_connection]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: üé® Checkout do reposit√≥rio
        uses: actions/checkout@v4

      - name: üîê Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ env.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

  # Job de Infraestrutura EKS para Deploy
  eks_infrastructure:
    name: üèóÔ∏è Provisionando EKS
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: üõ†Ô∏è Criar cluster EKS (se n√£o existir)
        run: |
          # Configura e provisiona o cluster EKS se necess√°rio

  # Job de Configura√ß√£o do ECR para Deploy
  ecr_setup:
    name: ü§ñ Provisionando ECR
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: üõ†Ô∏è Criar reposit√≥rio ECR (se n√£o existir)
        run: |
          # Configura e provisiona o reposit√≥rio ECR

  # Job de Build e Push da Imagem Docker
  docker_build_push:
    name: üêã Docker - Build & Push
    runs-on: ubuntu-latest
    needs: [ecr_setup, eks_infrastructure]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: üõ†Ô∏è Build da imagem Docker
        run: |
          docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest .

      - name: üè∑Ô∏è Tag da imagem
        run: |
          docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:${{ github.sha }}

      - name: üì§ Push da imagem Docker
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:${{ github.sha }}

  # Job de Deploy no EKS
  eks_deploy:
    name: üöÄ Deploy
    runs-on: ubuntu-latest
    needs: [eks_infrastructure, docker_build_push]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: ‚öôÔ∏è Configurar kubectl
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: üöÄ Atualizar deployment no EKS
        id: deploy
        run: |
          set -e
          kubectl set image deployment/$DEPLOYMENT_NAME tofood-container=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest || echo "rollback_needed=true" >> $GITHUB_ENV
          kubectl rollout status deployment/$DEPLOYMENT_NAME || echo "rollback_needed=true" >> $GITHUB_ENV

      - name: ‚ö†Ô∏è Rollback do deployment
        if: env.rollback_needed == 'true'
        run: |
          echo "Ocorreu algum erro ao tentar realizar o deploy na AWS, Restaurando a vers√£o anterior da imagem..."
          kubectl rollout undo deployment/$DEPLOYMENT_NAME

      - name: ‚úÖ Deployado
        if: env.rollback_needed != 'true'
        run: |
          echo "Deploy bem-sucedido!"
          # Obt√©m o hostname ou IP do LoadBalancer associado ao servi√ßo
          SERVICE_URL=$(kubectl get svc $DEPLOYMENT_NAME -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "URL de Produ√ß√£o: http://$SERVICE_URL"
          echo "Outras Informa√ß√µes Importantes:"
          kubectl get svc $DEPLOYMENT_NAME -o wide
          kubectl get nodes
